name: walkmoney
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  local_auth: ^2.3.0
  bubble_tab_indicator: ^0.1.4
  http: ^0.13.4
  enhanced_drop_down: ^0.1.7+1
  provider: ^6.0.1
  flutter_spinkit: ^5.2.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  path_provider: ^2.0.10
  timeline_tile: ^2.0.0
  flutter_highlight: ^0.7.0

  card_swiper: ^2.0.1
  mobile_scanner: ^3.5.0
  shared_preferences: ^2.0.15
  pie_chart: ^5.3.2
  carousel_slider: ^4.1.1
  card_loading: ^0.2.2
  camera: ^0.10.0
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^0.8.5+3
  image: ^3.2.0
  flutter_slidable: ^2.0.0
  dropdown_button2: ^1.8.9
  smooth_page_indicator: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^11.3.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11 # เครื่องมือสำหรับ generate code
  json_serializable: ^6.8.0 # ตัวสร้าง code สำหรับแปลง JSON

flutter:
  uses-material-design: true
  assets:
    - assets/images/
