name: walkmoney
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0

  http: ^0.13.4

  flutter_spinkit: ^5.2.0
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  path_provider: ^2.0.10

  card_swiper: ^2.0.1
  shared_preferences: ^2.0.15
  pie_chart: ^5.3.2
  card_loading: ^0.2.2
  camera: ^0.10.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_barcode_scanning: ^0.14.1
  image_picker: ^0.8.5+3
  image: ^4.5.4
  smooth_page_indicator: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^11.3.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11 # เครื่องมือสำหรับ generate code
  json_serializable: ^6.8.0 # ตัวสร้าง code สำหรับแปลง JSON
  flutter_launcher_icons: ^0.13.1 # สำหรับสร้าง app icon

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_walk2.png"
  min_sdk_android: 21
  # Android adaptive icon with blue background
  adaptive_icon_background: "#1565C0"
  adaptive_icon_foreground: "assets/images/logo_walk2.png"
  web:
    generate: true
    image_path: "assets/images/logo_walk2.png"
    background_color: "#1565C0"
    theme_color: "#1565C0"
  windows:
    generate: true
    image_path: "assets/images/logo_walk2.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo_walk2.png"
